project_id = "zddnvwqhfcqspmxscwyy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
additional_redirect_urls = ["https://127.0.0.1:3000/**"]
jwt_expiry = 3600
enable_signup = true

[functions.migrate-images-to-storage]
verify_jwt = false

[functions.cleanup-database]
verify_jwt = false

[functions.optimize-images]
verify_jwt = false

[functions.geocode-nominatim]
verify_jwt = false

[functions.batch-geocode-autorizados]
verify_jwt = false

[functions.emitir-nfse]
verify_jwt = true

[functions.emitir-nfe]
verify_jwt = true

[functions.consultar-nota]
verify_jwt = true

[functions.cancelar-nota]
verify_jwt = true

[functions.cancelar-nota-por-referencia]
verify_jwt = true

[functions.processar-postagens-agendadas]
verify_jwt = false

[functions.create-storage-bucket]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.init-pesquisas-satisfacao-bucket]
verify_jwt = false
